Treasure_Island = print("Welcome to Treasure Island")

print(" _ __ ___   ___  _ __   ___ _   _")
print("| '_ ` _ \ / _ \| '_ \ / _ \ | | |")
print("| | | | | | (_) | | | |  __/ |_| |")
print("|_| |_| |_|\___/|_| |_|\___|\__, |")
print("                             __/ |")
print("                            |___/ ")


direction = input("Choose a direction: Left or Right ")
direction.lower()
if direction == "right":
    print(r"\\\\\_____________________\"-._")
    print(r"/////~~~~~~~~~~~~~~~~~~~~~/.-'")

    print("     _            _   _     ")
    print("    | |          | | | |    ")
    print("  __| | ___  __ _| |_| |__  ")
    print(" / _` |/ _ \/ _` | __| '_ \ ")
    print("| (_| |  __/ (_| | |_| | | |")
    print(" \__,_|\___|\__,_|\__|_| |_|")

    print("You've fallen into a hole and died. Game Over.")
elif direction == "left":
    print(r"_.-'/______________________/////")
    print(r"`'-.\~~~~~~~~~~~~~~~~~~~~~~\\\\\'")

    swim_or_wait = input("Now you must choose: Swim or Wait ")
    swim_or_wait.lower()
    if swim_or_wait == "wait":
        print("        _____")
        print("     _.'_____`._")
        print("   .'.-'  12 `-.`.")
        print(r"  /,' 11      1 `.\"")
        print(r" // 10      /   2 \\")
        print(";;         /       ::")
        print("|| 9  ----O      3 ||")
        print("::                 ;;")
        print(r" \\ 8           4 //")
        print("  \`. 7       5 ,'/")
        print("   '.`-.__6__.-'.'")
        print("   ((-._____.-))")
        print("   _))       ((_")
        print("  '--'       '--'")

        print("You were attacked by a trout and died. Game Over.")

    elif swim_or_wait == "swim":
        print("                    ___")
        print(r"                   /___\"")
        print("               .-.|=0-0=|.-.")
        print(r"          (\_.'.-\ \_o_/`/-.'._/))")
        print("      ~` - ~`-^_`~ -_~ ^- ~_` -~ _")
        print("         -  ~  -  ^   - ~ -  ~  -")

        print("            __________ ")
        print("           |  __  __  |")
        print("           | |  ||  | |")
        print("           | |  ||  | |")
        print("           | |__||__| |")
        print("           |  __  __()|")
        print("           | |  ||  | |")
        print("           | |  ||  | |")
        print("           | |  ||  | |")
        print("           | |  ||  | |")
        print("           | |__||__| |")
        print("           |__________|")

        door = input("Choose a door to go through: Red, Blue, Yellow ")
        door.lower()

        if door == "yellow":
            print("                            _.--.")
            print("                        _.-'_:-'||")
            print("                    _.-'_.-::::'||")
            print("               _.-:'_.-::::::'  ||")
            print("             .'`-.-:::::::'     ||")
            print("            /.'`;|:::::::'      ||_")
            print("           ||   ||::::::'     _.;._'-._")
            print("           ||   ||:::::'  _.-!oo @.!-._'-.")
            print(r"          \'.  ||:::::.-!()oo @!()@.-'_.|")
            print(r"            '.'-;|:.-'.&$@.& ()$%-'o.'\U||")
            print("              `>'-.!@%()@'@_%-'_.-o _.|'||")
            print("               ||-._'-.@.-'_.-' _.-o  |'||")
            print(r"               ||=[ '-._.-\U/.-'    o |'||")
            print("               || '-.]=|| |'|      o  |'||")
            print("               ||      || |'|        _| ';")
            print("               ||      || |'|    _.-'_.-'")
            print("               |'-._   || |'|_.-'_.-'")
            print("                '-._'-.|| |' `_.-'")
            print("                    '-.||_/.-'")

            print("You win and secure the treasure!")
        elif door == "red":
            print("               (  .      )")
            print("           )           (              )")
            print("                 .  '   .   '  .  '  .")
            print("        (    , )       (.   )  (   ',    )")
            print("         .' ) ( . )    ,  ( ,     )   ( .")
            print("      ). , ( .   (  ) ( , ')  .' (  ,    )")
            print("     (_,) . ), ) _) _,')  (, ) '. )  ,. (' )")
            print("    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")

            print("You burned in a fire and died. Game Over.")
        elif door == "blue":
            print("  oo`'._..---.___..-")
            print(" (_,-.        ,..'`")
            print("      `'.    ;")
            print("         : :`")
            print("        _;_;       ")

            print("You were eaten by beasts and died. Game Over.")
        else:
            print("     .... NO! ...                  ... MNO! ...")
            print("   ..... MNO!! ...................... MNNOO! ...")
            print(" ..... MMNO! ......................... MNNOO!! .")
            print("..... MNOONNOO!   MMMMMMMMMMPPPOII!   MNNO!!!! .")
            print(" ... !O! NNO! MMMMMMMMMMMMMPPPOOOII!! NO! ....")
            print("    ...... ! MMMMMMMMMMMMMPPPPOOOOIII! ! ...")
            print("   ........ MMMMMMMMMMMMPPPPPOOOOOOII!! .....")
            print("   ........ MMMMMOOOOOOPPPPPPPPOOOOMII! ...")
            print("    ....... MMMMM..    OPPMMP    .,OMI! ....")
            print("     ...... MMMM::   o.,OPMP,.o   ::I!! ...")
            print("         .... NNM:::.,,OOPM!P,.::::!! ....")
            print("          .. MMNNNNNOOOOPMO!!IIPPO!!O! .....")
            print("         ... MMMMMNNNNOO:!!:!!IPPPPOO! ....")
            print("           .. MMMMMNNOOMMNNIIIPPPOO!! ......")
            print("          ...... MMMONNMMNNNIIIOO!..........")
            print("       ....... MN MOMMMNNNIIIIIO! OO ..........")
            print("  ...... NNN.MNO! . O!!!!!!!!!O . OONO NO! ........")
            print("   .... MNNNNNO! ...OOOOOOOOOOO .  MMNNON!........")
            print("   ...... MNNNNO! .. PPPPPPPPP .. MMNON!........")
            print("      ...... OO! ................. ON! .......")
            print("         ................................")


            print("Game Over.""")


